export const API_SLICE_MANAGEMENT = `https://5g-dashboard.i2cat.net/gw/slicemanagerapi`
export const API_SDK = `https://5g-dashboard.i2cat.net/gw/sdkapi`
export const API_ALERTS = `https://5g-dashboard.i2cat.net/gw/5gcityalertapi`
export const API_BASE_URL = `https://5g-dashboard.i2cat.net`
export const MEDIA_BASE_URL = `https://api.development.test`
export const SENTRY_URL = `https://eab890d8dc9d4493ae2db1a4d5d45b69@sentry2.ubiwhere.com/56`
export const API_MONITORING = `https://5gcity-monitoring.i2cat.net`
export const LOCATION = [ 2.175125, 41.386707 ]
export const AVAILABILITY_ZONE = ['compute_heavy', 'compute_light', 'edge-intel', 'edge-adlink'] // Implement
